name: "publish"

on:
  push:
    tags:
      - 'release/*'

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: publish
        run: echo ${{ github. }}
#      - name: publish
#        run: npm publish --access public
#        working-directory: .
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
