name: "publish"

on:
  push:
    tags:
      - 'release/*/v*.*.*'

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - uses: actions/github-script@v5
        id: extract-app
        with:
          script: |
            const reference = context.ref.split('/')[3]
            console.log(reference)
            return reference
          result-encoding: string
      - run: echo "${{ steps.extract-app.outputs.app_name }}"
#      - name: publish
#        run: npm publish --access public
#        working-directory: .
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

  # release/ci-tests/v0.1.