name: "publish"

on:
  push:
    tags:
      - 'release/*/v*.*.*'

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: extract-app
        uses: actions/github-script
        with:
          script: |
            const app_name = context.payload.ref_name.value.split('/')[1]
            core.setOutput('app_name', app_name)
      - run: echo "${{ github.ref_name }}"
      - run: echo "${{ steps.extract-app.outputs.app_name }}"
#      - name: publish
#        run: npm publish --access public
#        working-directory: .
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
